enabled: true
namespaceOverride: ""

replicaCount: 2

image:
  repository: registry.arca.local/arca-trust
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

serviceAccount:
  create: true
  name: ""
